### ISSUE TITLE
Next/previous class switch

### ISSUE THREAD

**Issue by thomas32426** [forward-pass/LabelBoundingBox#3]
It's difficult to remember which class corresponds to which number, so it would be nice if there was also a way to switch to the next/previous class.

I think ',' for previous and '.' for next makes sense.

**Comment by stoplime** [comment]
how about tab? and shift+tab?

**Comment by thomas32426** [comment]
I don't know if it's appropriate because your fingers are going to constantly be on the keys. I'd rather not hover on the side of the keyboard or use my pinky to switch.

**Comment by stoplime** [comment]
Yeah also the tab makes it go through the buttons on the window. but anyways it's done.
